### ISSUE TITLE
Viewer doesn't work on OSX

### ISSUE THREAD

**Issue by mineichen** [antonWetzel/treee#2]
I was abe to run the project with `cargo run -p treee --release` (without -p as suggested in readme doesnt work) and create the project. After selecting the project.epc, the application crashed. Starting the viewer with `cargo run -p viewer --release` failed too... Probably because of the Selector-Window

Tested with main-branch and version 0.0.2:

thread 'main' panicked at /Users/foo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/macos/event_loop.rs:200:13:
`winit` requires control over the principal class. You must create the event loop before other parts of your application initialize NSApplication
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

When replacing /viewer/main.rs with a static path, i get passed that error:
```rust
pub fn run(runner: &mut Runner) -> Result<(), Error> {
	let path = "/Users/mineichen/Downloads/treee_out/project.epc";

	let mut game = game::World::new(path.into(), runner).block_on()?;
	runner.run(&mut game)?;

	Ok(())
}
```

But run into a new one:

Tested with main-branch and version 0.0.2:

thread 'main' panicked at /Users/foo/rust/treee/render/src/state.rs:60:14:
called `Result::unwrap()` on an `Err` value: RequestDeviceError { inner: Core(UnsupportedFeature(Features(TIMESTAMP_QUERY))) }

**Comment by mineichen** [comment]
Once i remove the following from  /render/src/window.rs
```rust
let set = render_state
.device
.create_query_set(&wgpu::QuerySetDescriptor {
	label: None,
	ty: wgpu::QueryType::Timestamp,
	count: 2,
});
```
and  all related references to `set`, the scene is successfully written onto the screen... Would you consider to add this TimestampQuery as an optional Feature?

**Comment by antonWetzel** [comment]
I updated the viewer to start without a loaded project, I hope this fixes the event loop problem on macos.
I removed the time query and use just use the `delta` update time as render time.
If this does not fix the problems please reopen the issue.

**Comment by mineichen** [comment]
Both bugs are solved on osx with your changes, thanks
